[package]
name = "calendar"
version = "0.1.0"
authors = ["Amine <kurosoul.ae@gmail.com>"]
edition = "2018"

[dependencies]
image = "0.20.1"
imageproc = "0.17.0"
rusttype = "0.7.3"
rayon = "1.0.3"
exoquant = "0.2.0"
structopt = "0.2.14"